version: '3'

services:
  nginx:
    # используем последний стабильный образ nginx
    image: nginx:latest
    # маршрутизируем порты
    ports:
      - "8000:80"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    # nginx должен общаться с php контейнером
    links:
      - php
  php:
      # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
      build: ./images/php
      # этот образ будет общаться с mysql
      links:
        - mysql
      volumes:
        - ./www:/var/www
        - ./images/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        - ./images/php//volume:/usr/local/etc/php
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    # задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: secret
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - "8183:80"
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret